### ISSUE TITLE
[Request] Add reconnection after LoggedElseWhere

### ISSUE THREAD

**Issue by Havenstd06** [iValencitoh/Steam-Hour-Booster-2FA-Support#1]
Heyyy!

When I connect to the same game as the bot, the script disconnects the bot (normal) but it does not restart by itself, so is it possible to add a feature so that the bot reconnects everything alone and also when I relaunch the script that it does not yet request the steam guard code?

Thank you for your work !

**Comment by iValencitoh** [comment]
Heeyyy, sorry for my late answer, my bad, currently I'm working in other projects so I do not have time for working on this 😭 I think it is not possible to add an automatic reconnection (I would have to investigate it and/or try to do it)

Now about the Steam Guard code, is not possible, try to log in to your Steam account in Incognito mode with your browser, it will always ask for your Steam Guard code. (You can use your shared secret key to "automatically get" your code, you can find more information about it [here](https://github.com/SteamTimeIdler/stidler/wiki/Getting-your-'shared_secret'-code-for-use-with-Auto-Restarter-on-Mobile-Authentication))

Well thanks for using the booster and have a nice day buddy. 😄
