### ISSUE TITLE
Shared Secret is not working

### ISSUE THREAD

**Issue by mogelpeter** [iValencitoh/Steam-Hour-Booster-2FA-Support#10]
Just spams multiple codes into the console and ends with RateLimitExceeded.

Can you fix this`?

**Comment by valnssh** [comment]
Could you provide me with a screenshot of your config file? Be careful and redact any sensitive data.

The described issue looks like a duplicate of #4, maybe something is configured incorrectly?

**Comment by valnssh** [comment]
Closing this issue as completed after 2 weeks with no response from the OP.
