### ISSUE TITLE
Add restart function ?

### ISSUE THREAD

**Issue by shakeit1337** [iValencitoh/Steam-Hour-Booster-2FA-Support#18]
Maybe add auto restart option with not login off from this account

**Comment by valnssh** [comment]
Sorry, I didn't understand what you are proposing. Would you mind share me an example?

**Comment by shakeit1337** [comment]
Hello, so I have to log in again and again with the steam guard code as soon as I play on the account. is it possible for the account to start again without a steam guard code as soon as i go offline?

**Comment by valnssh** [comment]
This was a feature a while ago. I don't know when it stopped working, evidently I forgot to test sometime that I updated the dependencies.  
Anyway, this should be implemented on the latest commit.
