### ISSUE TITLE
How to use it on linux mate

### ISSUE THREAD

**Issue by kWAYTV** [iValencitoh/Steam-Hour-Booster-2FA-Support#2]
Entiendo español btw

**Comment by iValencitoh** [comment]
Necesitás de manera obligatoria [NodeJS](https://nodejs.org/), te recomiendo utilizar la versión [LTS](https://es.wikipedia.org/wiki/Soporte_de_largo_plazo) (actualmente 16.x). La forma de instalar NodeJS dependerá de tu distribución de Linux. Te recomiendo buscar algún artículo, creo que [DigitalOcean tenía uno para Ubuntu 20.04](https://www.digitalocean.com/community/tutorials/how-to-install-node-js-on-ubuntu-20-04#option-2-%E2%80%94-installing-node-js-with-apt-using-a-nodesource-ppa).

Una utilidad opcional sería `git` para clonar el repositorio, lo clonarías con el siguiente comando en un terminal: `git clone https://github.com/iValencitoh/Steam-Hour-Booster-2FA-Support.git`.

Otra opción es descargar el propio **.zip** desde Github.
![image](https://user-images.githubusercontent.com/24194163/151744391-682603a8-1921-4fed-bcff-c30533a701c8.png)
Luego, necesitarías descomprimir el archivo.

Una vez tengas NodeJS instalado y la aplicación descargada:
1. Entrás a la carpeta con los archivos de la aplicación. `cd Steam-Hour-Booster-2FA-Support`
2. Eliminas el archivo package-lock.json (información en el README.md). `rm package-lock.json`
3. Instalás las dependencias de la aplicación. `npm install`
4. Modificás los archivos de configuración (en la carpeta `config`).
5. Y por último ejecutás el programa con `npm run start`.

**Comment by kWAYTV** [comment]
![image](https://user-images.githubusercontent.com/55437151/151800763-e8ff12a4-3bbc-4540-bfea-3d3829d1e886.png)

**Comment by kWAYTV** [comment]
igual es  por que lo estoy intentando usar con pm2, si no,  como lo dejaria abierto teniendo otros procesos a la vez? Esque tengo bots de discord alojados aqui tambien

**Comment by kWAYTV** [comment]
Medio lo he solucionado usando screen pero me gustaria tenerlo todo en la misma ventana jaja

**Comment by iValencitoh** [comment]
Lo que sea que estés intentando usar para iniciar la aplicación no soporta [TTY](https://en.wikipedia.org/wiki/Tty_(Unix)). La dependencia [readline-sync](https://github.com/anseki/readline-sync) necesita poder acceder al TTY [para poder leer y escribir](https://github.com/anseki/readline-sync/issues/85#issuecomment-528375622).
La solución que te proporcionaría es la que ya realizaste, usá screen.
Escribís `screen -S booster` y repetís los pasos anteriormente mencionados. Utilizás `CTRL + A + D` para salir de la screen y `screen -x booster` para volver a la misma.
