### ISSUE TITLE
Problem when installing

### ISSUE THREAD

**Issue by Primoszz** [iValencitoh/Steam-Hour-Booster-2FA-Support#20]
There is a problem when installing the application: appdirectory@0.1.0: Package no longer supported
Please fix

**Comment by valnssh** [comment]
Hi there! What you see is a warning, not an error.  
The appdirectory package is being used as a dependency for [steam-user](https://github.com/DoctorMcKay/node-steam-user), not by my application.  
I encourage you to use the booster as intended, you shouldn't have any problems. ;)
