### ISSUE TITLE
How do i upgrade more than 32 games

### ISSUE THREAD

**Issue by ibrahimigdir** [iValencitoh/Steam-Hour-Booster-2FA-Support#28]
Hello, I am adding how I can add more than 32 games, but I am not boosting, unfortunately, you have made an explanation in the accountHandler.js file, but I could not understand it, because my English is bad, I would appreciate it if you could explain it visually or give a more detailed explanation, thank you.

**Comment by ibrahimigdir** [comment]
Let me add something
if (config.gamesAndStatus.length > 32)
When I change 32 in place, I can add games, I do not get an error message on the console, but no matter how many times I set the number of games after 32, the clock does not advance.

**Comment by AutismGaming228** [comment]
32 games is the maximum limit made by Steam, you can't go over it
