### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by FanyaOff** [iValencitoh/Steam-Hour-Booster-2FA-Support#3]
Whats wrong?
![Screenshot_1](https://user-images.githubusercontent.com/73064979/152634927-ce0a1088-c7c0-462c-b264-b8933fced745.png)

**Comment by valnssh** [comment]
Can you be more specific? (what version of NodeJS are you running?, what Linux distro are you using?, in which environment did the error originate?, what were your previous steps?)

I just did a fresh install in my Linux machine running Ubuntu Server 20.04 LTS and everything works perfectly fine.

**Comment by valnssh** [comment]
Closing this issue after 72 hours of inactivity by the OP.
