### ISSUE TITLE
It generate code itself?

### ISSUE THREAD

**Issue by gfghdg2233** [iValencitoh/Steam-Hour-Booster-2FA-Support#6]
https://imgur.com/a/GXzORuM

**Comment by uwu6967** [comment]
My system Linux openmediavault 5.16.0-0.bpo.4-amd64 #1 SMP PREEMPT Debian 5.16.12-1~bpo11+

**Comment by valnssh** [comment]
The code is automatically generated if you are using the shared secret key.  

By seeing the error, it is very likely that you have entered the shared secret key wrong. If you don't know what it is and/or how to obtain it, leave it blank.  
After that, the script will ask you to provide the 2FA code itself once you start it.

**Comment by uwu6967** [comment]
It was on blank

**Comment by valnssh** [comment]
Could you provide me with a screenshot of the configuration file?  
Be careful and redact any sensitive data.

**Comment by valnssh** [comment]
Closing this issue as completed after 2 weeks with no response from the OP.
