### ISSUE TITLE
Invalid password FIXED 

### ISSUE THREAD

**Issue by Ki4o112** [iValencitoh/Steam-Hour-Booster-2FA-Support#7]
Its says its invalid password but its in the account but i dont think its boosting hours in the games :( 
![image](https://user-images.githubusercontent.com/73773514/222899794-7c94c6bf-0056-453b-8c82-60c7bd871970.png)

**Comment by Ki4o112** [comment]
![image](https://user-images.githubusercontent.com/73773514/222899743-d113329c-0a2b-4572-adfa-1dbfe29365b7.png)
Here is the Config

**Comment by Ki4o112** [comment]
Never mind i fix it

**Comment by valnssh** [comment]
Closing this issue as completed since the OP said it's fixed.
